# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import agent_pb2 as agent_dot_v1_dot_agent__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in agent/v1/agent_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AgentStub(object):
    """── Agent service — vagent runs this, hermes-agent calls it ──
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Chat = channel.unary_stream(
                '/agent.v1.Agent/Chat',
                request_serializer=agent_dot_v1_dot_agent__pb2.ChatRequest.SerializeToString,
                response_deserializer=agent_dot_v1_dot_agent__pb2.ChatEvent.FromString,
                _registered_method=True)
        self.Ping = channel.unary_unary(
                '/agent.v1.Agent/Ping',
                request_serializer=agent_dot_v1_dot_agent__pb2.PingRequest.SerializeToString,
                response_deserializer=agent_dot_v1_dot_agent__pb2.PingResponse.FromString,
                _registered_method=True)


class AgentServicer(object):
    """── Agent service — vagent runs this, hermes-agent calls it ──
    """

    def Chat(self, request, context):
        """Full chat turn — server streams text / tool-batches / done back.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ping(self, request, context):
        """Health check.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Chat': grpc.unary_stream_rpc_method_handler(
                    servicer.Chat,
                    request_deserializer=agent_dot_v1_dot_agent__pb2.ChatRequest.FromString,
                    response_serializer=agent_dot_v1_dot_agent__pb2.ChatEvent.SerializeToString,
            ),
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=agent_dot_v1_dot_agent__pb2.PingRequest.FromString,
                    response_serializer=agent_dot_v1_dot_agent__pb2.PingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agent.v1.Agent', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('agent.v1.Agent', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Agent(object):
    """── Agent service — vagent runs this, hermes-agent calls it ──
    """

    @staticmethod
    def Chat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/agent.v1.Agent/Chat',
            agent_dot_v1_dot_agent__pb2.ChatRequest.SerializeToString,
            agent_dot_v1_dot_agent__pb2.ChatEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.v1.Agent/Ping',
            agent_dot_v1_dot_agent__pb2.PingRequest.SerializeToString,
            agent_dot_v1_dot_agent__pb2.PingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ToolExecutorStub(object):
    """── ToolExecutor service — hermes-agent runs this, vagent calls back ──
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Execute = channel.unary_unary(
                '/agent.v1.ToolExecutor/Execute',
                request_serializer=agent_dot_v1_dot_agent__pb2.ToolBatch.SerializeToString,
                response_deserializer=agent_dot_v1_dot_agent__pb2.ToolResults.FromString,
                _registered_method=True)


class ToolExecutorServicer(object):
    """── ToolExecutor service — hermes-agent runs this, vagent calls back ──
    """

    def Execute(self, request, context):
        """Execute a batch of tool calls, return all results.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ToolExecutorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Execute': grpc.unary_unary_rpc_method_handler(
                    servicer.Execute,
                    request_deserializer=agent_dot_v1_dot_agent__pb2.ToolBatch.FromString,
                    response_serializer=agent_dot_v1_dot_agent__pb2.ToolResults.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agent.v1.ToolExecutor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('agent.v1.ToolExecutor', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ToolExecutor(object):
    """── ToolExecutor service — hermes-agent runs this, vagent calls back ──
    """

    @staticmethod
    def Execute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.v1.ToolExecutor/Execute',
            agent_dot_v1_dot_agent__pb2.ToolBatch.SerializeToString,
            agent_dot_v1_dot_agent__pb2.ToolResults.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
